In [ ]:
import pandas as pd

url1 = 'https://data.insideairbnb.com/united-states/ny/new-york-city/2026-06-14/visualisations/neighbourhoods.csv'
pd.read_csv(url1).to_csv('data/neighbourhoods.csv')

url2 = 'https://data.insideairbnb.com/united-states/ny/new-york-city/2026-06-14/data/listings.csv.gz'
pd.read_csv(url2).to_csv('data/listings.csv.gz')

neighbourhoods = pd.read_csv("data/neighbourhoods.csv")
listings = pd.read_csv("data/listings.csv.gz")

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
neighbourhoods.head()

   Unnamed: 0 neighbourhood_group neighbourhood
0           0               Bronx      Allerton
1           1               Bronx    Baychester
2           2               Bronx       Belmont
3           3               Bronx     Bronxdale
4           4               Bronx   Castle Hill

In [10]:
listings.head()

,Unnamed: 0,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,2539,https://www.airbnb.com/rooms/2539,20260614073253,2026-06-15,city scrape,11 Min to Manhattan • Prospect Park • Fast WiFi,"Bright, serene room in a renovated apartment h...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,2787,https://www.airbnb.com/users/show/2787,1.462506e+18,https://www.airbnb.com/users/profile/146250632...,John,NaN,17.0,9.0,15.0,5.0,"New York, NY",Educated professional living in Brooklyn. I l...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,5.0,NaN,NaN,t,t,NaN,Kensington,Brooklyn,40.645937,-73.972164,Private room in condo,Private room,2,1.0,1 shared bath,1.0,2.0,"[""Bed linens"", ""Hot water"", ""Exterior security...",$113.97,2026-07-11,2026-08-10,3419.19,113.97,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",30.0,730.0,30.0,30.0,730.0,730.0,30.0,730.0,NaN,t,4,34,64,339,2026-06-15,10,1,1,174,0,60,6838.0,2015-12-04,2026-05-28,4.80,4.67,4.90,4.89,5.00,4.78,4.78,NaN,NaN,5,0,5,0,0.08
1,1,6848,https://www.airbnb.com/rooms/6848,20260614073253,2026-06-14,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,https://www.airbnb.com/users/show/15991,1.462507e+18,https://www.airbnb.com/users/profile/146250678...,Allen,NaN,17.0,1.0,15.0,5.0,"New York, NY",We love to travel. When we travel we like to s...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/15991/profile...,NaN,1.0,NaN,NaN,t,t,NaN,Williamsburg,Brooklyn,40.709350,-73.953420,Entire rental unit,Entire home/apt,3,1.0,1 bath,2.0,1.0,"[""Bed linens"", ""Hot water"", ""Fire extinguisher...",$117.27,2026-12-20,2027-01-19,3518.00,117.27,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",30.0,240.0,30.0,30.0,240.0,240.0,30.0,240.0,NaN,t,1,1,15,191,2026-06-14,198,3,0,27,4,180,21109.0,2009-05-25,2026-04-23,4.60,4.60,4.85,4.85,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.95
2,2,6872,https://www.airbnb.com/rooms/6872,20260614073253,2026-06-14,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,https://www.airbnb.com/users/show/16104,1.462507e+18,https://www.airbnb.com/users/profile/146250678...,Kae,NaN,17.0,1.0,15.0,5.0,"New York, NY",A former life in fashion and wellness has left...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/d865a...,NaN,2.0,NaN,NaN,t,t,NaN,East Harlem,Manhattan,40.801070,-73.942550,Private room in condo,Private room,1,1.0,1 shared bath,NaN,1.0,"[""Dryer"", ""Exterior security cameras on proper...",$80.06,2026-09-01,2026-10-01,2401.84,80.06,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",30.0,180.0,30.0,30.0,180.0,180.0,30.0,180.0,NaN,t,0,0,11,286,2026-06-14,2,1,0,122,1,60,4804.0,2022-06-05,2025-10-07,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
3,3,6990,https://www.airbnb.com/rooms/6990,20260614073253,2026-06-14,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,https://www.airbnb.com/users/show/16800,1.462507e+18,https://www.airbnb.com/users/profile/146250683...,Cynthia,NaN,17.0,1.0,15.0,5.0,"New York, NY",Capturing the Steinbeck side of life in its Fi...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/17c4d...,NaN,1.0,NaN,NaN,t,t,NaN,East Harlem,Manhattan,40.787780,-73.947590,Private room in rental unit,Private room,1,1.0,1 shared bath,NaN,1.0,"[""Bed linens"", ""Hot water"", ""Fire extinguisher...",$77.17,2026-12-06,2027-01-05,2315.00,77.17,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",30.0,120.0,30.0,30.0,120.0,120.0,30.0,120.0,NaN,t,0,28,28,218,2026-06-14,251,2,0,54,3,120,9260.0,2009-10-28,2026-01-11,4.88,4.83,4.95,4.96,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.24
4,4,7097,https://www.airbnb.com/rooms/7097,20260614073253,2026-06-14,city scrape,"Perfect for Your Parents, With Garden & Patio",Parents/grandparents coming to town or are you...,NaN,https://a0.muscache.com/pictures/aaac19fc-4b4d...,17571,https://www.airbnb.com/users/show/17571,1.462507e+18,https://www.airbnb.com/users/profile/146250684...,Jane,NaN,17.0,0.0,15.0,5.0,"New York, NY","I appreciate visitors and know New York well, ...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/18480...,NaN,2.0,NaN,NaN,t,t,NaN,Fort Greene,Brooklyn,40.691940,-73.973890,Private room in guest suite,Private room,2,1.0,1 private bath,NaN,2.0,"[""Bed linens"", ""Hot water"", ""Cleaning products...",$202.47,2027-02-28,2027-03-30,6074.17,202.47,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",30.0,1125.0,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,0,0,106,2026-06-14,423,10,0,0,28,255,51630.0,2010-01-16,2025-09-23,4.89,4.91,4.89,4.97,4.93,4.95,4.82,NaN,NaN,2,0,2,0,2.12

In [10]:
print(neighbourhoods.shape)
print('---------------------------------------')
print(neighbourhoods.columns.tolist())
print('---------------------------------------')
print(neighbourhoods.head())
print('---------------------------------------')
print(listings['neighbourhood_cleansed'].head())
print('---------------------------------------')
print(listings['neighbourhood_group_cleansed'].unique())

(230, 3)
---------------------------------------
['Unnamed: 0', 'neighbourhood_group', 'neighbourhood']
---------------------------------------
   Unnamed: 0 neighbourhood_group neighbourhood
0           0               Bronx      Allerton
1           1               Bronx    Baychester
2           2               Bronx       Belmont
3           3               Bronx     Bronxdale
4           4               Bronx   Castle Hill
---------------------------------------
0      Kensington
1    Williamsburg
2     East Harlem
3     East Harlem
4     Fort Greene
Name: neighbourhood_cleansed, dtype: str
---------------------------------------
<ArrowStringArray>
['Brooklyn', 'Manhattan', 'Queens', 'Bronx', 'Staten Island']
Length: 5, dtype: str

In [11]:
print(listings.shape)
print('---------------------------------------')
print(listings.columns.tolist())
print('---------------------------------------')
print(listings.dtypes)
print('---------------------------------------')
print(listings.isna().sum().sort_values(ascending=False).head(20))
print('---------------------------------------')
print(listings[['price']].head(10))
print('---------------------------------------')
print(listings['price'].dtype)

(30259, 91)
---------------------------------------
['Unnamed: 0', 'id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_total_price', 'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']
---------------------------------------
Unnamed: 0                                        int64
id                                                int64
listing_url                                         str
scrape_id                                         int64
last_scraped                                        str
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 91, dtype: object
---------------------------------------
neighborhood_overview          30259
host_acceptance_rate           30259
host_since                     30259
host_response_time             30259
host_thumbnail_url             30259
host_response_rate             30259
instant_bookable               30259
host_verifications             30259
neighbourhood                  30259
host_total_listings_count      30259
host_neighbourhood             30259
calendar_updated               30259
license                        24973
host_about                     12410
bedrooms                       10973
bathrooms                      10112
beds                            9420
price_quote_total_price         8745
price_quote_price_per_night     8745
price                           8744
dtype: int64
---------------------------------------
     price
0  $113.97
1  $117.27
2   $80.06
3   $77.17
4  $202.47
5  $365.97
6  $154.87
7   $91.07
8      NaN
9      NaN
---------------------------------------
str